#!/bin/bash

echo "========================================="
echo "🚀 GitHub & Docker Hub Push Guide"
echo "========================================="
echo ""

echo "📦 STEP 1: Push to GitHub"
echo "-------------------------"
echo "1. Create a new repository on GitHub:"
echo "   Go to: https://github.com/new"
echo "   Repository name: NPC"
echo "   Description: AI NPC System for RPG games with personality, memory, and quest generation"
echo "   Public repository"
echo "   Do NOT initialize with README (we already have one)"
echo ""
echo "2. Then run these commands:"
echo "   git remote add origin https://github.com/EchoSingh/NPC.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""

echo "🐳 STEP 2: Push to Docker Hub"
echo "-----------------------------"
echo "Run these commands:"
echo ""
echo "# Login to Docker Hub"
echo "docker login"
echo "# Username: aditya26062003"
echo "# Password: [your Docker Hub password]"
echo ""
echo "# Build the image"
echo "docker build -t aditya26062003/ai-npc-system:latest -t aditya26062003/ai-npc-system:1.0.0 ."
echo ""
echo "# Push to Docker Hub"
echo "docker push aditya26062003/ai-npc-system:latest"
echo "docker push aditya26062003/ai-npc-system:1.0.0"
echo ""

echo "✅ STEP 3: Verify"
echo "----------------"
echo "GitHub: https://github.com/EchoSingh/NPC"
echo "Docker Hub: https://hub.docker.com/r/aditya26062003/ai-npc-system"
echo ""

echo "🎯 STEP 4: Add GitHub Topics"
echo "---------------------------"
echo "Go to your GitHub repo and add these topics:"
echo "ai, npc, rpg, game-development, fastapi, llm, openai, redis, docker, python"
echo ""

echo "========================================="
echo "🎉 Ready to push!"
echo "========================================="
